virtualization_packages:
  - git
  - golang
  - gcc
  - make
  - python3-lxml
  - python3-netaddr
  - python3-libvirt
  - libvirt-devel
  - libvirt
  - qemu-kvm
  - virt-install
  - virt-manager

terraform_url: https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
libvirt_provider_repo: https://github.com/dmacvicar/terraform-provider-libvirt.git

centos_cloud_image: https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2
